### ISSUE TITLE
没有相关readme等说明文档么

### ISSUE THREAD

**Issue by it-noob** [lenvonsam/java-maven-selenium-demo#1]
一个 java、maven 集成 selenium 进行的 web 集成测试 demo，这个没有相关文档说明么？是集成测试什么呢？

**Comment by lenvonsam** [comment]
这个demo仅帮助搭建一个java+maven+selenium的框架，然后你安装一个firefox,java run-application就能看见selenium把你自动打开firefox输入你测试的网址，进行测试了，具体的selenium的api请参考官网

**Comment by it-noob** [comment]
@lenvonsam 好的，大概看了下，没看明白意思，抱歉，没有多查下资料。
